Repository Photory-Official/photory-server, pull requests merged in 2022-06, with the labels that each got.

#3 [FEAT] 로그인
  src/main/java/com/kale/config/SecurityConfig.java
  src/main/java/com/kale/controller/AuthController.java
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/dto/request/LoginUserReqDto.java
  src/main/java/com/kale/dto/response/LoginUserResDto.java
  src/main/java/com/kale/exception/InvalidPasswordException.java
  src/main/java/com/kale/exception/NotFoundEmailException.java
  src/main/java/com/kale/service/AuthService.java
Labels: ✨ Feature, 🐷 혁준 🐷

#5 [FEAT] 방 생성, 참가, 목록
  src/main/java/com/kale/config/security/JwtRequestFilter.java
  src/main/java/com/kale/controller/AuthController.java
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/controller/RoomController.java
  src/main/java/com/kale/dto/request/auth/LoginUserReqDto.java
  src/main/java/com/kale/dto/request/room/CreateRoomReqDto.java
  src/main/java/com/kale/dto/request/room/JoinRoomReqDto.java
  src/main/java/com/kale/dto/response/auth/LoginUserResDto.java
  src/main/java/com/kale/dto/response/room/CreateRoomResDto.java
  src/main/java/com/kale/dto/response/room/GetRoomsResDto.java
  src/main/java/com/kale/dto/response/room/JoinRoomResDto.java
  src/main/java/com/kale/exception/AlreadyInRoomException.java
  src/main/java/com/kale/exception/NotFoundRoomException.java
  src/main/java/com/kale/model/Participate.java
  src/main/java/com/kale/model/Room.java
  src/main/java/com/kale/repository/ParticipateRepository.java
  src/main/java/com/kale/repository/RoomRepository.java
  src/main/java/com/kale/service/RoomService.java
Labels: ✨ Feature, 🐷 혁준 🐷

#7 [FEAT] 로그인 유지
  src/main/java/com/kale/config/SecurityConfig.java
  src/main/java/com/kale/controller/AuthController.java
Labels: ✨ Feature, 🐷 혁준 🐷

#10 [FEAT] 방 나가기
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/controller/RoomController.java
  src/main/java/com/kale/exception/AlreadyNotInRoomException.java
  src/main/java/com/kale/repository/ParticipateRepository.java
  src/main/java/com/kale/service/RoomService.java
Labels: ✨ Feature, 🐷 혁준 🐷

#12 [FEAT] 방 나가기
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/exception/OwnerCanNotLeaveException.java
  src/main/java/com/kale/service/RoomService.java
Labels: ✨ Feature, 🐷 혁준 🐷

#13 [FEAT] 회원가입
  src/main/java/com/kale/controller/AuthController.java
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/dto/request/auth/AuthEmailCompleteReqDto.java
  src/main/java/com/kale/exception/IncorrectAuthKeyException.java
  src/main/java/com/kale/service/AuthService.java
  src/main/java/com/kale/util/RedisUtil.java
Labels: ✨ Feature, 🐼 예진 🐼

#15 [FEAT] 방 나가기 경고, 방 삭제, 방 인원 수
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/controller/RoomController.java
  src/main/java/com/kale/dto/request/room/DeleteRoomReqDto.java
  src/main/java/com/kale/dto/response/room/GetRoomsResDto.java
  src/main/java/com/kale/exception/AlertDeleteRoomException.java
  src/main/java/com/kale/exception/NotAloneException.java
  src/main/java/com/kale/exception/NotOwnerException.java
  src/main/java/com/kale/service/RoomService.java
Labels: ✨ Feature, 🐷 혁준 🐷

#17 [FEAT] 방 제약조건, 비밀번호 변경
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/controller/RoomController.java
  src/main/java/com/kale/dto/request/room/CreateRoomReqDto.java
  src/main/java/com/kale/dto/request/room/ModifyRoomPasswordReqDto.java
  src/main/java/com/kale/exception/NotInRoomException.java
  src/main/java/com/kale/model/Room.java
  src/main/java/com/kale/service/RoomService.java
Labels: ✨ Feature, 🐷 혁준 🐷

#22 [FEAT] 회원가입
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/exception/UnAuthenticatedEmailException.java
  src/main/java/com/kale/service/AuthService.java
Labels: ✨ Feature, 🐼 예진 🐼

#26 [FEAT] 사용자 강퇴, 방장 위임
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/controller/RoomController.java
  src/main/java/com/kale/dto/request/room/DelegateOwnerReqDto.java
  src/main/java/com/kale/dto/request/room/DeleteUserForceReqDto.java
  src/main/java/com/kale/exception/UserAlreadyNotInRoomException.java
  src/main/java/com/kale/model/Room.java
  src/main/java/com/kale/service/RoomService.java
Labels: ✨ Feature, 🐼 예진 🐼

#29 [REFACTOR] dto 서비스에서 처리
  src/main/java/com/kale/controller/AuthController.java
  src/main/java/com/kale/controller/RoomController.java
  src/main/java/com/kale/service/AuthService.java
  src/main/java/com/kale/service/RoomService.java
Labels: 🔨 Refactor, 🐷 혁준 🐷

#31 [TEST] createRoom 성공 테스트
  src/main/java/com/kale/dto/request/room/CreateRoomReqDto.java
  src/main/java/com/kale/repository/RoomRepository.java
  src/test/java/com/kale/service/RoomServiceTest.java
Labels: ✅ Test, 🐷 혁준 🐷

#35 [FEAT] 피드 생성
  build.gradle
  src/main/java/com/kale/config/S3Config.java
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/controller/FeedController.java
  src/main/java/com/kale/domain/Feed.java
  src/main/java/com/kale/domain/FeedImage.java
  src/main/java/com/kale/exception/ImageUploadFailedException.java
  src/main/java/com/kale/exception/InvalidFileException.java
  src/main/java/com/kale/repository/FeedImageRepository.java
  src/main/java/com/kale/repository/FeedRepository.java
  src/main/java/com/kale/service/FeedService.java
  src/main/java/com/kale/service/FeedServiceUtils.java
  src/main/java/com/kale/service/S3Service.java
  src/main/java/com/kale/util/JwtUtil.java
  src/main/java/com/kale/util/YamlPropertySourceFactory.java
Labels: ✨ Feature, 🐷 혁준 🐷

#37 [FEAT] 피드 수정
  src/main/java/com/kale/controller/ExceptionController.java
  src/main/java/com/kale/controller/FeedController.java
  src/main/java/com/kale/domain/Feed.java
  src/main/java/com/kale/dto/request/feed/ModifyFeedReqDto.java
  src/main/java/com/kale/dto/response/feed/ModifyFeedResDto.java
  src/main/java/com/kale/exception/NotFeedOwnerException.java
  src/main/java/com/kale/exception/NotFoundFeedException.java
  src/main/java/com/kale/repository/FeedImageRepository.java
  src/main/java/com/kale/service/FeedService.java
Labels: ✨ Feature, 🐷 혁준 🐷
